services:
  postgres:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    container_name: ecommify_postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MasterPassword2026!
      POSTGRES_DB: ecommify
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./postgresql/schema:/docker-entrypoint-initdb.d
    networks:
      - ecommify_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommify"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: ecommify_mongodb_local
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoRootPass2026!
      MONGO_INITDB_DATABASE: ecommify
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d:ro
    networks:
      - ecommify_net
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ecommify_net:
    driver: bridge
